[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

[[redirects]]
from = "/blog/*"
to = "/.netlify/functions/meta-renderer"
status = 200
force = true
query = { _escaped_fragment = ":fragment" }
conditions = { UserAgent = ["linkedinbot", "twitterbot", "slackbot", "facebookexternalhit/"] }  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  # CRITICAL FIX: This line forces Netlify to find and bundle the dependency.
  external_node_modules = ["@supabase/supabase-js"] 